name: Automated checks

on: [push]

jobs:
  hackage-compat-check:
    name: Check the package for Hackage compatibility
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Check the package
        run: cabal check
  builds:
    name: Build the package with all specified compilers
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Build the package
        uses: jeltsch/actions-cabal-build@master
